privacyUrl: /kontakt/datenschutz
hashtag: '#tarteaucitron'
cookieName: tarteaucitron
orientation: middle
showAlertSmall: 'true'
cookieslist: 'true'
adblocker: 'true'
AcceptAllCta: 'false'
highPrivacy: 'true'
handleBrowserDNTRequest: 'false'
removeCredit: 'true'
moreInfoLink: 'true'
useExternalCss: 'false'
cookieDomain: ''
readmoreLink: ''
crazyeggId: ''
google_analytics_ga_js: ''
google_analytics_gtag_js: ''
google_analytics_gtag_js_multiple: ''
google_analytics_universal: ''
google_adwordsremarketingId: ''
google_fonts_families: ''
google_tag_manager: ''
hubspot_api_key: ''
ekomi_cert_id: ''
etracker: ''
facebook_pixel_id: '12343452345'
matomo_site_id: ''
matomo_host: ''
mautic_url: ''
zopimID: ''
