pimcore_install:
  parameters:
    database_credentials:
      user:                 db
      password:             db
      dbname:               db

      # env variables can be directly read with the %env() syntax
      # see https://symfony.com/blog/new-in-symfony-3-2-runtime-environment-variables
      host:                 db