services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # ---------------------------------------------------------
    # Link Generators for DataObjects
    # ---------------------------------------------------------

    AppBundle\Website\LinkGenerator\CategoryLinkGenerator:
        public: true


        # ---------------------------------------------------------
        # Twig Extensions
        # ---------------------------------------------------------

        #AppBundle\Twig\Extension\NavigationExtension:
        #tags: ['twig.extension']

    AppBundle\Twig\Extension\ConectoExtension:
        tags: ['twig.extension']

    #AppBundle\Twig\Extension\NavExtension:
    #    tags: ['twig.extension']

    AppBundle\Twig\Extension\LanguageSwitcherExtension:
        tags: ['twig.extension']

    #AppBundle\Twig\Extension\CountryListExtension:
    #    tags: ['twig.extension']

#    AppBundle\Twig\Extension\LanguageSwitcherExtension:
#        tags: ['twig.extension']
